# -*- coding: utf-8 -*-
"""NO_RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X2eb4EECJJiLLTjBkJyrPutZ-BKtdUB6
"""

!pip install -U langchain-community -q

!pip install --upgrade langchain langchain-openai openai
!pip install --upgrade langchain langchain-openai langchain-community openai

!pip install chromadb

!pip install langchain openai chromadb tiktoken -q
# 📦 Install dependencies (run this first)
!pip install requests beautifulsoup4 tqdm
!pip install langchain-google-genai

!pip install langchain-openai

"""# Step 1: Defining the Case and Ontology Scaffold"""

case_links = [
    {
        "case_id": "Case 1",
        "description": "A 3-year-old girl presents with generalized hypotonia, intellectual disability, and delayed motor milestones. She has limited verbal skills and exhibits apathy and autistic-like features. On physical exam, she has midface retrusion and synophrys. Sleep difficulties are also reported.",
        "age_of_onset": "Infancy to early childhood",
        "sex": "Female",
        "hpo_terms": {
            "HP:0001252": "Hypotonia",
            "HP:0001249": "Intellectual disability",
            "HP:0002194": "Delayed gross motor development",
            "HP:0005957": "Breathing dysregulation",
            "HP:0000729": "Autistic behavior",
            "HP:0001999": "Abnormal Facial Shape",
            "HP:0002360": "Sleep Abnormality"
        },
        "provisional_diagnosis": "Kleefstra Syndrome"
    }
]

"""Think of this like a hierarchy:
 Symptom → HPO → Ontology Category → Clinical System

 Ex: "HP:0001276" → "Abnormality of speech" → "Neurologic"

# Step 2: Construct the Prompt
"""

def build_zero_shot_prompt(case):
    hpo_lines = "\n".join([f"- {hpo} – {desc}" for hpo, desc in case["hpo_terms"].items()])
    prompt = f"""You are a clinical reasoning assistant tasked with identifying rare disease diagnoses based solely on phenotypic features presented in a patient vignette.
Please analyze the following case and arrive at the most likely diagnosis.

Step 1: Identify the key symptoms from the vignette.
Step 2: Use clinical reasoning to group these symptoms.
Step 3: Generate a list of possible differential diagnoses.
Step 4: Select and justify the most likely diagnosis.


Case:
{case['description']}

HPO terms:
{hpo_lines}

Please begin your reasoning."""
    return(prompt)
    #print(prompt)

prompt = build_zero_shot_prompt(case_links[0])

import os
import json
from langchain_openai import ChatOpenAI
from langchain.prompts import PromptTemplate

from dotenv import load_dotenv
load_dotenv()
# Set OPENAI_API_KEY in your .env file

# 💬 Setup OpenAI chat model
llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0.3)

# 🧾 Define prompt template
no_rag_prompt_template = PromptTemplate(
    input_variables=["case_description", "hpo_terms"],
    template="""
You are a clinical reasoning assistant tasked with identifying rare disease diagnoses based solely on phenotypic features presented in a patient vignette.
Please analyze the following case and arrive at the most likely diagnosis.

Step 1: Identify the key symptoms from the vignette.
Step 2: Use clinical reasoning to group these symptoms.
Step 3: Generate a list of possible differential diagnoses.
Step 4: Select and justify the most likely diagnosis.

Case:
{case_description}

HPO terms:
{hpo_terms}

Please begin your reasoning.
"""
)

"""# Send To LLM API"""

# 🚀 Function to run diagnosis without RAG
def run_zero_shot_diagnosis(case):
    case_description = case["description"]
    hpo_terms = "\n".join([f"- {k} – {v}" for k, v in case["hpo_terms"].items()])

    prompt = no_rag_prompt_template.format(
        case_description=case_description,
        hpo_terms=hpo_terms
    )

    print("🔍 Prompt:\n", prompt)
    response = llm.invoke(prompt)
    print("\n🧠 Model Output:\n", response.content)

# 🧪 Example test case
case = {
    "description": "A 3-year-old girl presents with generalized hypotonia, intellectual disability, and delayed motor milestones. She has limited verbal skills and exhibits apathy and autistic-like features. On physical exam, she has midface retrusion and synophrys. Sleep difficulties are also reported.",
    "hpo_terms": {
        "HP:0001252": "Hypotonia",
        "HP:0001249": "Intellectual disability",
        "HP:0002194": "Delayed gross motor development",
        "HP:0005957": "Breathing dysregulation",
        "HP:0000729": "Autistic behavior",
        "HP:0001999": "Abnormal Facial Shape",
        "HP:0002360": "Sleep Abnormality"
    }
}

run_zero_shot_diagnosis(case_links[0])