# -*- coding: utf-8 -*-
"""RAG_ONTOLOGY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13TyUyKegxWs1Uyq7Kvv49k5tVzi3fC5z
"""



# ---------------- STEP 1: PubMed Retrieval ----------------

!pip install biopython --quiet

import os
from Bio import Entrez, Medline
import pandas as pd
from dotenv import load_dotenv
load_dotenv()

Entrez.email = os.getenv("ENTREZ_EMAIL", "your-email@example.com")

# Sample HPO and ontology categories from case
hpo_terms = [
    "hypotonia",
    "intellectual disability",
    "delayed gross motor development",
    "autistic behavior",
    "abnormal facial shape",
    "sleep abnormality"
]
ontology_categories = ["Cognitive", "Craniofacial / Dysmorphia", "Motor"]

def build_diagnosis_free_query(hpo_terms, ontology_categories):
    return f"({' OR '.join(hpo_terms)}) OR ({' OR '.join(ontology_categories)})"

def search_pubmed(query, max_results=50):
    handle = Entrez.esearch(db="pubmed", term=query, retmax=max_results)
    record = Entrez.read(handle)
    handle.close()
    return record["IdList"]

def fetch_articles(pmids):
    if not pmids:
        return []
    handle = Entrez.efetch(db="pubmed", id=",".join(pmids), rettype="medline", retmode="text")
    records = list(Medline.parse(handle))
    handle.close()
    return records

def articles_to_df(records):
    return pd.DataFrame([{
        "PMID": rec.get("PMID", ""),
        "Title": rec.get("TI", ""),
        "Abstract": rec.get("AB", ""),
        "Authors": ", ".join(rec.get("AU", [])),
        "Journal": rec.get("JT", ""),
        "Year": rec.get("DP", "")
    } for rec in records if "AB" in rec and len(rec["AB"]) > 100])

query = build_diagnosis_free_query(hpo_terms, ontology_categories)
pmids = search_pubmed(query)
records = fetch_articles(pmids)
df = articles_to_df(records)
print(f"✅ Retrieved {len(df)} usable abstracts.")

!pip install -U langchain langchain-openai

# ---------------- STEP 2: Vector Embedding into Chroma ----------------

!pip install langchain langchain-community chromadb openai tiktoken --quiet

import os
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain.prompts import PromptTemplate

from dotenv import load_dotenv
load_dotenv()
# Set OPENAI_API_KEY in your .env file

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=150)
docs = []

for _, row in df.iterrows():
    chunks = text_splitter.create_documents(
        texts=[row["Abstract"]],
        metadatas=[{
            "pmid": row["PMID"],
            "title": row["Title"],
            "authors": row["Authors"],
            "journal": row["Journal"],
            "year": row["Year"]
        }]
    )
    docs.extend(chunks)

embedding_model = OpenAIEmbeddings(model="text-embedding-3-small")
vectorstore = Chroma.from_documents(docs, embedding_model, persist_directory="rag_pubmed_db")
vectorstore.persist()
retriever = vectorstore.as_retriever()
llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0.3)

# ---------------- STEP 3: Ontology-aware RAG + CoT Prompt ----------------

# Ontology map (you can import this from a .py or .json too)
ontology_map = {
    "Rett Syndrome": ["Cognitive", "Motor", "Speech / Language", "Seizure / Epilepsy", "Behavioral", "Developmental Regression"],
    "Dravet Syndrome": ["Seizure / Epilepsy", "Cognitive", "Developmental Regression"],
    "Pelizaeus–Merzbacher Disease": ["Motor", "Neuromuscular", "Cognitive"],
    "MECP2 Duplication Syndrome": ["Cognitive", "Seizure / Epilepsy", "Motor"],
    "Ataxia–Telangiectasia": ["Motor", "Immune / Infectious", "Cardiac / Vascular"],
    "Lesch–Nyhan Syndrome": ["Behavioral", "Motor", "Cognitive"],
    "Phelan–McDermid Syndrome": ["Speech / Language", "Behavioral", "Cognitive"],
    "Smith–Magenis Syndrome": ["Behavioral", "Cognitive", "Speech / Language"],
    "Kleefstra Syndrome": ["Cognitive", "Craniofacial / Dysmorphia", "Motor"],
    "Maple Syrup Urine Disease": ["Metabolic", "Cognitive"],
    "Glutaric Aciduria Type I": ["Metabolic", "Developmental Regression"],
    "MELAS Syndrome": ["Metabolic", "Neuromuscular", "Cognitive"],
    "Zellweger Spectrum Disorder": ["Metabolic", "Sensory", "Cognitive"],
    "Brugada Syndrome": ["Cardiac / Vascular"],
    "Hereditary Hemorrhagic Telangiectasia (HHT)": ["Cardiac / Vascular"],
    "Ehlers–Danlos Syndrome (vascular type)": ["Skeletal / Orthopedic", "Cardiac / Vascular"],
    "Paroxysmal Nocturnal Hemoglobinuria (PNH)": ["Hematologic"],
    "Osteogenesis Imperfecta Type I or III": ["Skeletal / Orthopedic", "Sensory"],
    "Thanatophoric Dysplasia": ["Skeletal / Orthopedic"],
    "Mucopolysaccharidosis Type I (Hurler Syndrome)": ["Cognitive", "Skeletal / Orthopedic", "Craniofacial / Dysmorphia"],
    "Hyper IgE Syndrome (Job’s Syndrome)": ["Immune / Infectious"],
    "Chronic Granulomatous Disease": ["Immune / Infectious"],
    "Chediak–Higashi Syndrome": ["Immune / Infectious", "Sensory"],
    "Usher Syndrome Type I": ["Sensory"],
    "Leber Hereditary Optic Neuropathy (LHON)": ["Sensory"],
    "Retinitis Pigmentosa": ["Sensory"],
    "Congenital Adrenal Hyperplasia": ["Endocrine / Growth"],
    "Beckwith–Wiedemann Syndrome": ["Endocrine / Growth", "Cognitive"],
    "Sotos Syndrome": ["Endocrine / Growth", "Cognitive"],
    "Angelman Syndrome": ["Cognitive", "Behavioral", "Seizure / Epilepsy"],
    "Stiff–Person Syndrome": ["Motor", "Pain"],
    "Fabry Disease": ["Metabolic", "Pain", "Cardiac / Vascular"],
    "Niemann–Pick Type C": ["Cognitive", "Developmental Regression", "Metabolic"],
    "Moebius Syndrome": ["Craniofacial / Dysmorphia", "Motor"]
}

# Prompt template with ontology scaffold
rag_prompt_template = PromptTemplate(
    input_variables=["case_description", "hpo_terms", "ontology_scaffold", "retrieved_context"],
    template="""
You are a clinical reasoning assistant tasked with diagnosing rare diseases using phenotypic features, structured ontology information, and supporting biomedical literature. Please reason step-by-step using the following structure.

Ontology Scaffold:
Body System(s): {ontology_scaffold}
Symptom Categories: (from HPO terms)

**Retrieved Literature:**
{retrieved_context}

Please reason step-by-step using both the ontology scaffold and the retrieved evidence.

Step 1: List the input symptoms and their mapped HPO terms.
Step 2: Map each HPO term to its corresponding clinical system.
Step 3: Group symptoms into potential disease categories.
Step 4: Generate a differential diagnosis list based on the above.
Step 5: Select the most likely diagnosis.
Step 6: Justify your reasoning using both ontology alignment and the literature (cite key evidence).
Step 7: Clearly state the final diagnosis.

Case Description:
{case_description}
"""
)

# Case Input
case = {
    "case_id": "Case 1",
    "description": "A 3-year-old girl presents with generalized hypotonia, intellectual disability, and delayed motor milestones. She has limited verbal skills and exhibits apathy and autistic-like features. On physical exam, she has midface retrusion and synophrys. Sleep difficulties are also reported.",
    "hpo_terms": {
        "HP:0001252": "Hypotonia",
        "HP:0001249": "Intellectual disability",
        "HP:0002194": "Delayed gross motor development",
        "HP:0005957": "Breathing dysregulation",
        "HP:0000729": "Autistic behavior",
        "HP:0001999": "Abnormal Facial Shape",
        "HP:0002360": "Sleep Abnormality"
    },
    "ontology": ["Cognitive", "Motor", "Craniofacial / Dysmorphia"]
}

# Run RAG diagnosis with ontology-aware prompt
def get_unique_pmids(docs, num_unique):
    seen = set()
    unique_docs = []
    for doc in docs:
        pmid = doc.metadata.get("pmid")
        if pmid not in seen:
            seen.add(pmid)
            unique_docs.append(doc)
        if len(unique_docs) == num_unique:
            break
    return unique_docs

def run_rag_diagnosis(case, num_unique_pmids=5):
    case_description = case["description"]
    hpo_terms = "\n".join([f"- {k}: {v}" for k, v in case["hpo_terms"].items()])
    ontology_scaffold = ", ".join(case["ontology"])

    all_docs = retriever.vectorstore.similarity_search(case_description, k=30)
    retrieved_docs = get_unique_pmids(all_docs, num_unique_pmids)
    retrieved_context = "\n---\n".join([doc.page_content for doc in retrieved_docs])

    final_prompt = rag_prompt_template.format(
        case_description=case_description,
        hpo_terms=hpo_terms,
        ontology_scaffold=ontology_scaffold,
        retrieved_context=retrieved_context
    )

    print(f"📋 Final Prompt with {num_unique_pmids} unique abstracts:\n")
    print(final_prompt)
    print("\n📚 Source Abstracts Used:")
    for doc in retrieved_docs:
        print(f"- PMID {doc.metadata['pmid']}: {doc.metadata['title'][:90]}...")

    response = llm.invoke(final_prompt)
    print("\n🧠 Diagnosis Output:\n", response.content)

# 🔁 Run it (change 5 to 1 or 3 as needed)
run_rag_diagnosis(case, num_unique_pmids=5)