# -*- coding: utf-8 -*-
"""RAG_N_docs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eXKDmW2YKJEmdihd41hHtqxD7tox-Yky
"""

!pip install -U langchain-community -q

!pip install --upgrade langchain langchain-openai openai
!pip install --upgrade langchain langchain-openai langchain-community openai

!pip install chromadb

!pip install langchain openai chromadb tiktoken -q
# 📦 Install dependencies (run this first)
!pip install requests beautifulsoup4 tqdm
!pip install langchain-google-genai

# ------------------ STEP 1: PubMed Search + Fetch ------------------

!pip install biopython --quiet

import os
from Bio import Entrez, Medline
import pandas as pd
from dotenv import load_dotenv
load_dotenv()

Entrez.email = os.getenv("ENTREZ_EMAIL", "your-email@example.com")

# HPO terms for the case
hpo_terms = [
    "hypotonia",
    "intellectual disability",
    "delayed gross motor development",
    "autistic behavior",
    "abnormal facial shape",
    "sleep abnormality"
]
ontology_categories = ["Cognitive", "Craniofacial / Dysmorphia", "Motor"]

def build_diagnosis_free_query(hpo_terms, ontology_categories):
    hpo_part = " OR ".join(hpo_terms)
    category_part = " OR ".join(ontology_categories)
    return f"({hpo_part}) OR ({category_part})"

def search_pubmed(query, max_results=30):
    handle = Entrez.esearch(db="pubmed", term=query, retmax=max_results)
    record = Entrez.read(handle)
    handle.close()
    return record["IdList"]

def fetch_articles(pmids):
    if not pmids:
        return []
    handle = Entrez.efetch(db="pubmed", id=",".join(pmids), rettype="medline", retmode="text")
    records = list(Medline.parse(handle))
    handle.close()
    return records

def articles_to_df(records):
    data = []
    for rec in records:
        data.append({
            "PMID": rec.get("PMID", ""),
            "Title": rec.get("TI", ""),
            "Abstract": rec.get("AB", ""),
            "Authors": ", ".join(rec.get("AU", [])),
            "Journal": rec.get("JT", ""),
            "Year": rec.get("DP", "")
        })
    return pd.DataFrame(data)

query = build_diagnosis_free_query(hpo_terms, ontology_categories)
pmids = search_pubmed(query)
records = fetch_articles(pmids)
df = articles_to_df(records)
df.to_csv("pubmed_results.csv", index=False)
print(f"✅ Retrieved {len(df)} abstracts.")

# ------------------ STEP 2: Embed Abstracts into Chroma Vectorstore ------------------

!pip install langchain langchain-community chromadb openai tiktoken --quiet

import os
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain.prompts import PromptTemplate

from dotenv import load_dotenv
load_dotenv()
# Set OPENAI_API_KEY in your .env file

# Split abstracts into chunks
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=150)
all_chunks = []

for idx, row in df.iterrows():
    abstract = row["Abstract"]
    if not isinstance(abstract, str) or len(abstract.strip()) < 10:
        continue

    chunks = text_splitter.create_documents(
        texts=[abstract],
        metadatas=[{
            "pmid": row["PMID"],
            "title": row["Title"],
            "authors": row["Authors"],
            "journal": row["Journal"],
            "year": row["Year"]
        }]
    )
    all_chunks.extend(chunks)

print(f"✅ Total Chunks: {len(all_chunks)}")

embedding_model = OpenAIEmbeddings(model="text-embedding-3-small")
vectorstore = Chroma.from_documents(all_chunks, embedding_model, persist_directory="rag_pubmed_db")
vectorstore.persist()
retriever = vectorstore.as_retriever()
llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0.3)

# ------------------ STEP 3: Run Diagnosis w/ Unique Abstract Control ------------------

# Helper to get N unique PMIDs
from collections import defaultdict

def get_unique_pmids(docs, num_unique):
    seen = set()
    unique_docs = []
    for doc in docs:
        pmid = doc.metadata.get("pmid")
        if pmid not in seen:
            seen.add(pmid)
            unique_docs.append(doc)
        if len(unique_docs) == num_unique:
            break
    return unique_docs

# Sample case input
case = {
    "case_id": "Case 1",
    "description": "A 3-year-old girl presents with generalized hypotonia, intellectual disability, and delayed motor milestones. She has limited verbal skills and exhibits apathy and autistic-like features. On physical exam, she has midface retrusion and synophrys. Sleep difficulties are also reported.",
    "hpo_terms": {
        "HP:0001252": "Hypotonia",
        "HP:0001249": "Intellectual disability",
        "HP:0002194": "Delayed gross motor development",
        "HP:0005957": "Breathing dysregulation",
        "HP:0000729": "Autistic behavior",
        "HP:0001999": "Abnormal Facial Shape",
        "HP:0002360": "Sleep Abnormality"
    }
}

# Prompt Template with HPO
rag_prompt_template = PromptTemplate(
    input_variables=["case_description", "hpo_terms", "retrieved_context"],
    template="""
You are a clinical reasoning assistant tasked with identifying rare disease diagnoses using patient phenotypic data and relevant literature.

**Retrieved Literature:**
{retrieved_context}

Use both the case details and the literature below to reason through possible diagnoses.

Case Description:
{case_description}

Mapped HPO Terms:
{hpo_terms}

Step 1: List key symptoms mentioned in the case.
Step 2: Refer to the literature and note any overlapping conditions or key patterns.
Step 3: Generate a list of potential differential diagnoses based on case + literature.
Step 4: Choose and justify the most likely diagnosis, referencing specific literature passages when appropriate.
"""
)

def run_rag_diagnosis(case, num_unique_pmids=5):
    case_description = case["description"]
    hpo_terms = "\n".join([f"- {k}: {v}" for k, v in case["hpo_terms"].items()])

    # Get lots of docs, then filter by unique PMIDs
    # Overfetch 30 chunks to increase chances of unique PMIDs
    all_docs = retriever.vectorstore.similarity_search(case_description, k=30)
    retrieved_docs = get_unique_pmids(all_docs, num_unique_pmids)
    retrieved_context = "\n---\n".join([doc.page_content for doc in retrieved_docs])

    prompt = rag_prompt_template.format(
        case_description=case_description,
        hpo_terms=hpo_terms,
        retrieved_context=retrieved_context
    )

    print(f"📋 Final Prompt with {num_unique_pmids} unique abstracts:\n")
    print(prompt)
    print("\n📚 Source Abstracts Used:")
    for doc in retrieved_docs:
        print(f"- PMID {doc.metadata['pmid']}: {doc.metadata['title'][:90]}...")

    response = llm.invoke(prompt)
    print("\n🧠 Diagnosis Output:\n", response.content)

# 🔁 Run with different settings
run_rag_diagnosis(case, num_unique_pmids=3)  # Change to 1 or 3 to test smaller inputs